version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --character-set-server=utf8 --collation-server=utf8_bin --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - zabbix-net
    volumes:
      - zabbix-mysql-data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 10051:10051 
    networks:
      - zabbix-net
      
  zabbix-web-server:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix-web-server
    restart: unless-stopped
    depends_on:
      - mysql
      - zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      ZBX_SERVER_HOST: zabbix-server
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 80:8080
    networks:
      - zabbix-net
      
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.0-latest
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - 10050:10050
    networks:
      - zabbix-net
      
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - mysql
      - zabbix-server
      - zabbix-web-server
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app
    ports:
      - 3000:3000
    networks:
      - zabbix-net
    volumes:
      - zabbix-grafana-data:/var/lib/grafana

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge
    name: zabbix-net

volumes:
  zabbix-mysql-data:
    name: zabbix-mysql-data
  zabbix-grafana-data:
    name: zabbix-grafana-data